version: '3.9'
services:
  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=NoteDB;User=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: notes-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
